layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      comments: true

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
   facebook: noonanhe
  # hackerrank: your_username
   instagram: _eathe_
  # keybase: your_username
   linkedin: heathergnoonan
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: JavaScript
    web_url: https://www.javascript.com/
    image_url: images/javascript-logo.png

  - name: Web design
    web_url: https://en.wikipedia.org/wiki/Web_design
    image_url: images/web design.jpg

  - name: Machine Learning
    web_url: https://en.wikipedia.org/wiki/Machine_learning
    image_url: images/machine learning.png

podcasts:
  - name: The Daily
    web_url: https://www.nytimes.com/column/the-daily
    image_url: images/the_daily.png
    description: A podcast by the New York Times that provides 20-30 minute investigations into current news stories.
    
  - name: My Favorite Murder
    web_url: https://myfavoritemurder.com
    image_url: images/my_fave_murder.png
    description: A True Crime Podcast where the 2 hilarious hosts cover murder, cult, and other crime stories.
    
  - name: Business Wars
    web_url: https://wondery.com/shows/business-wars
    image_url: images/business_wars.png
    description: This podcast does little mini series of about 6-7 episodes covering the histories of some of today's biggest corporate rivalries. 

resume: true

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
# staticman_url: https://${bridge_app_name}.herokuapp.com/v2/entry/${github-username}/${blog-repo}/master/comments
staticman_url: https://staticman-comments.herokuapp.com/v2/entry/noonanhe/noonanhe.gitub.io/master/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  siteKey: 6Lc8VfsUAAAAAG9ZSsv6EcKYaohGt4NT6IPSwh4M
  secret: cbrCO/qUxmozMg65UFkjTPpSA908ThMAhLQZBdEkocciZHnrN5A72Cl81ddriq8qkWofWxiRWOywo3yOQNsXMR+JYxGEnglIQ/H3yzaARWtTLWaFGiHMnsLdHQFS+Rd/B26zrUZg9cY6St8QVDfc7sOqcx0/iTuzk5oYJsC93as=
